### ISSUE TITLE
OAuth認証の追加

### ISSUE THREAD

**Issue by tohutohu** [traPtitech/traQ#100]

**Comment by wtks** [comment]
鯖側が発行したアクセストークンってウェブクライアント(traQ-UI)側でどう保持するんですかね？

**Comment by wtks** [comment]
OAuthのレスポンスに含まれてるアクセストークンをクライアント側のjsでLocalStorageで保存するって感じなのかな

**Comment by tohutohu** [comment]
traQ-UIではoauyhしないでいいと思います

**Comment by wtks** [comment]
Implicit Grantはセキュリティ上の理由でサポートしないことにします。

**Comment by wtks** [comment]
認可画面どうしよう。traQ-UIに組み込むか、鯖側が独自のページを配信するか。
未ログイン時にはログイン画面→認可画面のフローの実装も必要。

**Comment by wtks** [comment]
OpenID Connectにも対応させます
