### ISSUE TITLE
Echoのバージョンをあげる

### ISSUE THREAD

**Issue by wtks** [traPtitech/traQ#1010]
#1001 

Routerのバグで無限ループが起こってCPU使用率が100%に張り付いてた
https://github.com/labstack/echo/issues/1493

**Comment by motoki317** [comment]
上のissueはv4.1.15で直ってそう
https://github.com/labstack/echo/compare/v4.1.14...v4.1.15

#1119 でこのテストが落ちてるのは、上の変更で少し挙動が変わってるからっぽそう
https://github.com/traPtitech/traQ/blob/e7d7fe140b170e0e0263e907be49a87fdde40c1b/router/v1/public_test.go#L28-L34
