### ISSUE TITLE
クッキーがあるけど凍結されてるときのレスポンスを凍結されてますにする

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/traQ#1051]
https://github.com/traPtitech/traQ/blob/5f63529535d8fe6f0a3e42701e2589f712347b39/router/auth/provider.go#L69-L71

**Comment by hijiki51** [comment]
このdefaultLoginHandlerが呼ばれるのってどういう状況ですか…（再現できない）

**Comment by sapphi-red** [comment]
https://github.com/traPtitech/traQ/blob/5f63529535d8fe6f0a3e42701e2589f712347b39/router/auth/provider.go#L173-L175
ごめんなさい、こっちかもしれない…

**Comment by sapphi-red** [comment]
いや嘘これかも
https://github.com/traPtitech/traQ/blob/d96d4814569ca26f827469ac9c2ca29a48027429/router/v3/sessions.go#L63

**Comment by sapphi-red** [comment]
で、補足でこのissueは

- 有効なクッキーが保持されている
- そのクッキーのユーザーが凍結されている

という条件で`You have already logged in. Please logout once.`が返ってくるのでそれを`this account is currently suspended`にしたいっていうissueです

**Comment by hijiki51** [comment]
クッキーっていうのはr_sessionをさしていますか？(あとこれがあるときってsessionが保持されているのと同値ですか？)

**Comment by FujishigeTemma** [comment]
cookieは`r_session`であってます。
言ってるのは「`r_session`が(クライアント側に)あるとき」だと思うんだけど、ここで言う「有効なcookieが保持されている」ってのは「`r_session`の値に該当するセッションがtraQのサーバー(session store)に`session.Expired() == false`な状態で存在する」ことだと思う。
https://github.com/traPtitech/traQ/blob/master/router/session/session.go

**Comment by hijiki51** [comment]
だとしたら
https://github.com/traPtitech/traQ/blob/d96d4814569ca26f827469ac9c2ca29a48027429/router/middlewares/no_login.go
ここら辺書き換えればいいですかね？(session有効時はここに飛んでそうなんですが…)

**Comment by sapphi-red** [comment]
あ、それです(ハンドラの適用の順番勘違いしてました 🙇 )
