### ISSUE TITLE
統計API

### ISSUE THREAD

**Issue by motoki317** [traPtitech/traQ#1057]
あったら面白そう

データベースを叩いて集計する系の
`/channels/{channelId}/stats`のような感じで

- チャンネルごとに
  - メッセージ数
  - スタンプ毎の押したスタンプの数
  - ユーザー毎のメッセージ数
- ユーザーごとに
  - (DMを含む)メッセージ数
  - (DMを含む)スタンプごとの押したスタンプの数
- スタンプごとに
  - (DMを含む)押された回数

スタンプを押した回数は、一人複数回押したらそれを複数回と一回とカウントするかも考える

**Comment by sapphi-red** [comment]
refs #670

**Comment by sapphi-red** [comment]
```sql
SELECT `stamp_id`, COUNT(`message_id`) as `message_count`, SUM(`count`) as `total_count` FROM `messages_stamps` GROUP BY `stamp_id` ORDER BY `total_count` DESC LIMIT 5
```
https://wiki.trap.jp/user/sappi_red/memo/2020/08/07/traQ_stamps

**Comment by ghost** [comment]
hikokubo0923です。QSoCで取り組みます。
