### ISSUE TITLE
PullRequestのActionsで謎のLint Checkが走りっぱなしになる

### ISSUE THREAD

**Issue by wtks** [traPtitech/traQ#1075]
![-well-known-change-passwordへの対応-close-1070-by-sapphi-red-·-Pull-Request-1074-·-traPtitech-traQ](https://user-images.githubusercontent.com/30363887/106357030-fb4e3800-6346-11eb-93e4-a08c2602a9ff.png)
なにこれ

**Comment by cskd8** [comment]
Rerunしたら通りました

**Comment by wtks** [comment]
🤔

**Comment by sapphi-red** [comment]
> Run golangci-lint run --out-format=line-number | reviewdog -f=golangci-lint -name=golangci-lint -reporter=github-check
level=error msg="Timeout exceeded: try increasing it by passing --timeout option"
2021/04/19 10:01:47 [golangci-lint] reported: https://github.com/traPtitech/traQ/runs/2379671209 (conclusion=success)

https://github.com/traPtitech/traQ/runs/2379657998

これかなり怪しそう

**Comment by motoki317** [comment]
ギリギリ1分かかるかかからないかくらいだったのかな

**Comment by sapphi-red** [comment]
たぶん

**Comment by motoki317** [comment]
直ってなかった :Hyperblob:
https://github.com/traPtitech/traQ/pull/1146/checks?check_run_id=2380237327

**Comment by sapphi-red** [comment]
:Hyperblob:

**Comment by logica0419** [comment]
最近起きてないのでとりあえずClose
