### ISSUE TITLE
引用通知を飛ばす情報を変える

### ISSUE THREAD

**Issue by hijiki51** [traPtitech/traQ#1112]
イベントで飛ばすのではなくメッセージ作成時のイベントで自分のメッセージが引用されているかどうかを情報として持つように変更する

**Comment by sapphi-red** [comment]
> 今(クライアントでは)`MESSAGE_CREATED`のうち条件を満たしていたときに未読に追加しているのですが、`MESSAGE_CITED`も未読に追加すると重複して未読が追加されることがあるので、`MESSAGE_CREATED`に`is_cited`のフラグを追加して、それが`true`のものはアクティビティが全チャンネルでなくても送る、というようにしてほしいです

**Comment by wtks** [comment]
`is_cited`じゃなくて`is_citing`が合ってると思う

**Comment by motoki317** [comment]
分かりやすくするなら `is_citing_me` `cites_me` とかでしょうか
