### ISSUE TITLE
CIのTBLSが落ちる

### ISSUE THREAD

**Issue by motoki317** [traPtitech/traQ#1145]
> /home/runner/work/_temp/c0395c39-1329-425c-84bf-6f8234ac93e8.sh: line 4: tbls: command not found

急に壊れた(?)

https://github.com/traPtitech/traQ/runs/2379192313?check_suite_focus=true

**Comment by motoki317** [comment]
何回かrerunしたら直った :thinking:

**Comment by sapphi-red** [comment]
たぶんネットワークの問題
