### ISSUE TITLE
GET /api/v3/stampsのレスポンスにhasThumbnailを含める

### ISSUE THREAD

**Issue by motoki317** [traPtitech/traQ#1154]
サムネイル画像を代わりに表示するため

(レスポンスが)正規化されないのでちょっと気持ち悪い

**Comment by azbcww** [comment]
これってv7file構造体のようにHasThumbailを追加したStamp構造体に修正するのか，レスポンスの直前のデータにhasThumbnailを追加するのか，どちらを想定していますか？

**Comment by logica0419** [comment]
サムネイルの情報を取得するのが、コンピューター視点でどれくらい大変かによるかなぁと思います

(前提として、言ってくれたStamp構造体はDBの構造(スキーマ)を定義している構造体です)

基本的にはわざわざDBに入れると更新の手間が増えてしまうのでその場で取得という形にしてほしいです
ただ、もしサムネイルを持っているかどうかの判定がめちゃくちゃ重くてまともに使えないというレベルであれば、DBに入れておくのはアリな戦略です(多分今回はそんなことないと思いますが)

とりあえず、サムネイルがあるかどうか判定するロジックがすでにtraQにあるはずなので、それを探すところからやってみて下さい〜

**Comment by azbcww** [comment]
ありがとうございます！了解です！
とりあえずロジック探してみますー

**Comment by azbcww** [comment]
draft作成したので時間に余裕あるとき見てもらいたいです
