### ISSUE TITLE
/api/1.0 の廃止

### ISSUE THREAD

**Issue by motoki317** [traPtitech/traQ#1158]
/public 以外あまり使われていなさそうなので、検討する

廃止するにしても周知期間は必要

**Comment by sapphi-red** [comment]
blocked by traPtitech/knoQ#40

**Comment by sapphi-red** [comment]
https://github.com/traPtitech/traQ/blob/0b606e7a4790cf7f6f81d532e5eda8b1dd88f4b6/router/auth/traq.go#L104-L105
ここv1のままになってる

**Comment by motoki317** [comment]
↑は直した

**Comment by motoki317** [comment]
`/api/1.0/public`, `/api/1.0/files`, `/api/1.0/files/:fid/thumbnail` を残して削除する
