### ISSUE TITLE
デフォルトでチャンネルを一つ生やしておく

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/traQ#1172]
#generalだけは初回起動時に存在しててよさそう

**Comment by motoki317** [comment]
生えそうな気がするけど生えなかった？
https://github.com/traPtitech/traQ/blob/64ad56bd7df4625f7804051c590a8bf430a9610b/cmd/serve.go#L109

**Comment by sapphi-red** [comment]
https://github.com/traPtitech/traQ/blob/64ad56bd7df4625f7804051c590a8bf430a9610b/repository/repository_impl.go#L30
あーじゃたぶん、`init`が`false`になることがあるっぽい？

**Comment by motoki317** [comment]
今Adminユーザーが一人も居ない場合initがtrueになって初期化処理が走るけど、schemaの初期化↓を条件にした方が良いかも
https://github.com/traPtitech/traQ/blob/64ad56bd7df4625f7804051c590a8bf430a9610b/migration/migrate.go#L21
