### ISSUE TITLE
pin API の修正

### ISSUE THREAD

**Issue by kaz** [traPtitech/traQ#119]
## want
- pinにIDを付与
- pinしたユーザー情報を保存
- pinした日時を保存

## todo
- [x] swaggey.yaml 修正
- [x] db_schema.md 修正

## note
- 最近 @yasu0001 がinactive
- 現行pinブランチが古い

ので、pinの実装も @AzonTi にReassginするのが妥当かと思うんですが、どうですか？

**Comment by azonti** [comment]
僕はOKです
やりましょう

**Comment by kaz** [comment]
#123
