### ISSUE TITLE
`DELETE /groups/{groupId}/admins/{userId}`で最後のグループ管理者を削除したときに204が返ってくる

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/traQ#1195]
https://apis.trap.jp/#/group/removeUserGroupAdmin

> グループから管理者が存在しなくなる場合は400エラーを返します。

仕様的には400が返ってくるはず

**Comment by motoki317** [comment]
ア
https://github.com/traPtitech/traQ/blob/76d8d34d55085898dc1f6d344ec7ba926136811d/repository/user_group_impl.go#L287
