### ISSUE TITLE
Webhookをグループの管理者に追加できる

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/traQ#1199]
できないべきな気がする

**Comment by sapphi-red** [comment]
メンバーもできないべきな気がする

**Comment by motoki317** [comment]
BOTをグループに追加したいことってある？

**Comment by FujishigeTemma** [comment]
ぱっと思いつきはしないし、なくて良さそう
Groupを対象に取る機能が増えたらなんか変わるかもだけど、その時はもう一回考えれば良いとおもう
