### ISSUE TITLE
GET /file/{fileId}/thumbnailの実装

### ISSUE THREAD

**Issue by masutech16** [traPtitech/traQ#121]

**Comment by kaz** [comment]
- [x] `POST /files`のRequest bodyの説明、もっといい感じに表示できないかな？？
- [x] swagger.yamlの`GET /file/{fileId}/thumbnail`がtypoしてる
- [x] `GET /files/{fileID}?dl=1`とかしたら`Content-Disposition: attachment; filename=****`みたいなヘッダがつくようにしてほしい

**Comment by wtks** [comment]
とりあえず、画像のサムネイル生成ならPure Goなライブラリを用いれば実装できるので画像はする。
動画に関してはffmpegとか使わないと行けないと思うので後回しで
