### ISSUE TITLE
アクティビティの`per_channel=true`のときに含まれるべきメッセージが含まれない

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/traQ#1218]
`per_channel=false`のときに

- channelAのメッセージ
- channelBのメッセージ
- channelBのメッセージ

が表示されるのに

`per_channel=true`のときに

- channelAのメッセージ

だけしか表示されない

ともに`all=true`

**Comment by motoki317** [comment]
再現方法が分からない

**Comment by sapphi-red** [comment]
今みたら起きてなかった、謎です

**Comment by motoki317** [comment]
再現しないのでとりあえずcloseします
`channel_latest_messages`とかで何か不整合が起こったのかもしれないが分からない
