### ISSUE TITLE
全アカウントに初期状態でクリップフォルダを1つ用意してほしい

### ISSUE THREAD

**Issue by logica0419** [traPtitech/traQ#1225]
クリップはフォルダがないと使えない機能だって知らなくて永遠に虚空をタップしてたことがあったので、YouTubeの「後で見る」再生リスト的な発想で、初期状態で「クリップ」とか適当な名前を付けた空フォルダが一つ存在してほしい
初期状態でクリップ機能使えるようにする案は2~3個思いつきますが、多分これが一番早いと思います

**Comment by motoki317** [comment]
下で解決したりはしませんか？
refs https://github.com/traPtitech/traQ_S-UI/issues/758
https://q.trap.jp/messages/207384aa-b7bd-438f-9248-5fbac1a69e68

**Comment by logica0419** [comment]
> 下で解決したりはしませんか？
> refs [traPtitech/traQ_S-UI#758](https://github.com/traPtitech/traQ_S-UI/issues/758)
> https://q.trap.jp/messages/207384aa-b7bd-438f-9248-5fbac1a69e68

あ、多分それでいいですね…
