### ISSUE TITLE
開発環境へのログイン手段

### ISSUE THREAD

**Issue by motoki317** [traPtitech/traQ#1243]
## 現状

開発環境（traq-s-dev.tokyotech.org）へ、traQ_S-UIのローカルの開発環境（localhost）からログインするとき、ログインの手段が
- 一旦traq-s-dev.tokyotech.orgで正攻法（本家traQのOAuth2なり）でログインしてから、`r_session`をlocalhostに手動貼る

ということをしている

## 目的

何らかの方法でログイン手段を確保したい

- ログインのための(traQ)OAuth2クライアントを2つ以上用意できるようにして、callback URLがtraq-s-dev.tokyotech.orgとlocalhostのものを使い分ける

**Comment by sapphi-red** [comment]
~~#1330 でやる~~

**Comment by sapphi-red** [comment]
https://wiki.trap.jp/SysAd/dev/traQ/#head3

**Comment by motoki317** [comment]
開発環境を`q-dev.trapti.tech`以下に移し、`traP_token`を用いた認証(caddy-trap-auth)を`POST /api/v3/users`のみにかけることで（一旦）解決した。
https://q.trap.jp/messages/0086269f-9941-4876-a710-81024be39de5
