### ISSUE TITLE
WebSocketの`CHANNEL_CREATED`イベントでDMの場合は相手ユーザーUUIDの情報も送信する

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/traQ#1247]
traPtitech/traQ_S-UI#2326 の解決に必要

**Comment by motoki317** [comment]
こんなんで良いかな（自分へのDMの場合は長さ1、そうでないDMの場合は長さ2の配列が飛んでくる）

        ### `CHANNEL_CREATED`
        チャンネルが新規作成された。

        対象: 該当チャンネルを閲覧可能な全員

        + `id`: 作成されたチャンネルのId
        + `private_members`: プライベートチャンネルの場合チャンネルを閲覧可能なユーザーIdの配列

        ### `CHANNEL_UPDATED`
        チャンネルの情報が変更された。

        対象: 該当チャンネルを閲覧可能な全員

        + `id`: 変更があったチャンネルのId
        + `private_members`: プライベートチャンネルの場合チャンネルを閲覧可能なユーザーIdの配列

        ### `CHANNEL_DELETED`
        チャンネルが削除された。

        対象: 該当チャンネルを閲覧可能な全員

        + `id`: 削除されたチャンネルのId
        + `private_members`: プライベートチャンネルの場合チャンネルを閲覧可能なユーザーIdの配列

**Comment by sapphi-red** [comment]
自分へのDM以外は知れないほうがよくない？今も知れない情報だし

**Comment by motoki317** [comment]
自分が入っているDM(プライベートチャンネル)以外は情報飛んでこないけど分かりにくいところあったかな

**Comment by sapphi-red** [comment]
このそうでないDMってのがわかってない

> 自分へのDMの場合は長さ1、そうでないDMの場合は長さ2の配列が飛んでくる

3人以上の(今は存在しない)プライベートチャンネルのこと？

**Comment by motoki317** [comment]
あ、その意味は自分へのDM（自分しかメンバーが存在しないDMチャンネル）の場合は自分のIDの長さ1で、そうでない普通のDMの場合は自分と相手のIDという意味でした

**Comment by sapphi-red** [comment]
あ、理解

**Comment by sapphi-red** [comment]
@motoki317 やっぱり`/api/v3/channels`との一貫性的に`private_members`には自分自身は含めないでほしい :pray: (自分宛のDMじゃない場合)

**Comment by motoki317** [comment]
それは分かるけど(実装的に)ちょっと面倒なんだよね
それに自分宛てのDMの場合はprivate_membersに自分が入るということ？（それの方が一貫性無い気がする）

**Comment by motoki317** [comment]
それとも配列じゃなくて相手のIDを入れる？

**Comment by sapphi-red** [comment]
相手のIDを入れる

**Comment by sapphi-red** [comment]
https://apis.trap.jp/#/channel/getChannels
これで`dm`のとこが`{id: チャンネルID, userId: 相手}`になってるからそう扱わないとフロント側ごっちゃごちゃになるから避けたい
