### ISSUE TITLE
ユーザーidの置換の有無

### ISSUE THREAD

**Issue by n-inja** [traPtitech/traQ#135]
現行traQと同じ仕様 {user: } にしますか

**Comment by kaz** [comment]
Slackっぽくしたみがある
Slackは、`<ID|元の文字列>`になっていて、例えばユーザ名やチャンネル名が変更された場合でも、テキスト自体は変化しないようになっている

**Comment by kaz** [comment]
拡張できるように文中に`開始パターン+JSON`で埋め込めるみたいなのはどうだろう
たとえば`!{"type":"link","ref":"/user/hoge","text":"@hoge"}`とか
ファイルへのリンクを文中に埋め込んだり、他色々な拡張に利用できそう

**Comment by wtks** [comment]
今後は #146 で
