### ISSUE TITLE
[GET] stars

### ISSUE THREAD

**Issue by n-inja** [traPtitech/traQ#139]
すでに登録したチャンネルを登録しようとするとエラーを吐くが
GETだと空配列が返ってくる

**Comment by tohutohu** [comment]
自分の環境だと再現しませんでした
手順としては
POSTで登録(できた)
GETで取得(１件帰ってきた)
POSTで同じチャンネルを登録しようとする(エラー)
GETで取得(１件帰ってきた)

**Comment by n-inja** [comment]
同じく再現できなかったので勘違いだったかもしれません
クローズします
