### ISSUE TITLE
id、タグの埋め込み形式

### ISSUE THREAD

**Issue by n-inja** [traPtitech/traQ#146]
クライアント側では
 - ユーザー
 - タグ
 - 添付ファイル
 - チャンネル

で #135 のような埋め込み形式を使いたいのですが、サーバー側で拾うものに関して形式を合わせておきたいです。

**Comment by n-inja** [comment]
``` txt
!{
  "type": "user" | "tag" | "file" + mimetype | "channel",
  "raw": 元の文字列,
  "id": typeに応じたID
}
```
のような形式を構想しています。

**Comment by wtks** [comment]
"file" + mimetypeのmimetypeは要らなくていいと思います

**Comment by kaz** [comment]
これ置換して埋め込むのってサーバサイドですか？クライアントサイドですか？
私はクライアントが良いと思う
