### ISSUE TITLE
Spectral Actionが落ちたことに気づけない

### ISSUE THREAD

**Issue by logica0419** [traPtitech/traQ#1468]
https://github.com/traPtitech/traQ/runs/6662307100?check_suite_focus=true#step:4:8

`Resource not accessible by integration`エラーだそう

**Comment by sapphi-red** [comment]
そのrunは他リポジトリのやつから発火されたものなので、それ関連ですね
https://github.com/traPtitech/traQ/actions/runs/2411816165

masterのは動いてるので壊れても最悪気づくことはできそうです
https://github.com/traPtitech/traQ/actions/workflows/swagger-change.yml?query=branch%3Amaster

**Comment by logica0419** [comment]
あ～なるほど
他リポジトリからの発火で権限が無いのか…

**Comment by logica0419** [comment]
ただ、動いてないのにsuccessマークが付いてるのは問題な気がするのでIssueに残しておきます
https://github.com/stoplightio/spectral-action/issues/183
https://github.com/stoplightio/spectral-action/issues/624
https://github.com/stoplightio/spectral-action/issues/626
ここら辺に書かれているけど、使っているactionsの仕様として
- 設定のミスがあってもpassにしてしまう
- spectralが悪い部分を見つけても、warningにするだけでpassにしてしまう

という仕様があるので、自力で書いた方が良い説が出ている
