### ISSUE TITLE
チャンネル検索

### ISSUE THREAD

**Issue by wtks** [traPtitech/traQ#15]

**Comment by tohutohu** [comment]
これってサーバーにクエリ投げて検索するようなことあるんですかね
チャンネル名だけならクライアント側でやってもらったほうが良さそう
Topic入れるなら考えなくもないけど私はクライアント側推しです

**Comment by wtks** [comment]
僕もサーバー側で実装する必要ないと思います

**Comment by tohutohu** [comment]
ではクローズで
