### ISSUE TITLE
userの更新関数がない

### ISSUE THREAD

**Issue by masutech16** [traPtitech/traQ#159]
statusやアイコンを更新する関数がないので追加した方が良さそうです。apiも同様に。

また、現在はuserを作る際にiconのIDが必要ですが、iconのIDの中身であるfileIDはdbでcreatorIDを外部キーに持っているため現状のfile→userの順に追加するとエラーが起こるみたいです。

この問題は最初にダミーアイコンのようなものを指定してuserを作成。その後、アイコンをdbに入れて、それを上で追加する予定のupdateを用いて置換してやれば解決しそうです。が、ほかにも方法がありそうなので何かご存知の方がいればここにお願いします。

**Comment by wtks** [comment]
直します
