### ISSUE TITLE
チャンネルを開いていてもフォーカスしていない時は通知が来て欲しい

### ISSUE THREAD

**Issue by motoki317** [traPtitech/traQ#1638]
今はウィンドウをフォーカスしているかに関わらずこないので

フロントもどれくらい改修が必要かは調べてない

**Comment by logica0419** [comment]
コード読む限り、フォーカスしているかどうかのステータスを今サーバー側で持っていないはずなので、選択肢は
- フォーカスしているかどうかをサーバーが保存してそれをつかう
- フォーカスしていなければ「チャンネルを見ていない」という扱いにする(おそらくサイドバーのチャンネル閲覧中表示になど、他の部分にも影響するようになる)

ですね

**Comment by mehm8128** [comment]
https://github.com/traPtitech/traQ_S-UI/issues/861
これがnoneのときにフォーカスしていないっていう扱いではないですか？
「noneにすると未読に追加されるので、表示したときに既読にする必要がある」の「未読に追加される」が通知も飛んでくることであればサーバーで新たに変えることはなさそうな気がしています

**Comment by motoki317** [comment]
> [traPtitech/traQ_S-UI#861](https://github.com/traPtitech/traQ_S-UI/issues/861) これがnoneのときにフォーカスしていないっていう扱いではないですか？ 「noneにすると未読に追加されるので、表示したときに既読にする必要がある」の「未読に追加される」が通知も飛んでくることであればサーバーで新たに変えることはなさそうな気がしています

あーそうですね、issueにあったの見てなかったです（感謝）
"none"がバックグラウンド表示っていうのは分かりにくいから今なら変えても良いかもですね...

その上で、 https://github.com/traPtitech/traQ_S-UI/issues/1735 がデザイン設計も入った、表示するためのissueでしたね
これはじゃあcloseしますね
