### ISSUE TITLE
テストが遅い

### ISSUE THREAD

**Issue by wtks** [traPtitech/traQ#169]
テスト毎にDB全部吹き飛ばしてるから。
並列できるような書き方がしたい

**Comment by tohutohu** [comment]
それぞれのテストのすべてのDBでスタブ的なのを使うことができればOKそう(選択肢としてはsqlite3使うとか？)

**Comment by wtks** [comment]
https://github.com/DATA-DOG/go-sqlmock
`database/sql`のdriverのmockがあった。ただ、実行したSQLクエリに対しての応答を全部定義しないと行けないから取得系のテストしか並列化できなさそう

**Comment by wtks** [comment]
modelのテストはdbとの接続込みのテストだから実際のdb使ってなんとか並列化しないと行けないけど、routerのテストはhttpハンドラのテストだから、dbに接続する必要がなくてモック使えばいいんだよな

**Comment by wtks** [comment]
いずれにせよmodelをインターフェイス経由で操作するように書き直す必要はありそう

**Comment by wtks** [comment]
カバレッジの出力を切るか、カバレッジ出力ありのgo testのキャッシュが効くようになれば(go 1.12マイルストーン)、テストのキャッシュが効いて実行する必要のない成功テストをスキップするようになるので大幅に早くなる。

**Comment by wtks** [comment]
#365 サブテストを利用してmodelのテストを並列化

**Comment by wtks** [comment]
テスト3分ぐらいで終わるようになった
