### ISSUE TITLE
添付ファイルのアップロード

### ISSUE THREAD

**Issue by wtks** [traPtitech/traQ#18]
- 一度にアップロードするファイルの数は任意
- ファイル容量設定は管理者が設定可能
- サーバ側でサムネイルを作成
- ファイルのURL: `/file/{fileId}`
- メタURL:`/file/{fileId}/meta`
- サムネイルのURL: `/file/{fileId}/thumbnail`
    - ~~メタデータはメッセージに載せる~~
    - クライアント側で逐次取る

**Comment by kaz** [comment]
# swaggerに追加スべき

`POST /file`
`GET /file/{fileId}`
`DELETE /file/{fileId}`
`GET /file/{fileId}/meta`
`GET /file/{fileId}/thumbnail`

# 備考
- thumbnailの実装は後でいい
- Fileデータの読み書き部はinterfaceを定義して抽象化

**Comment by masutech16** [comment]
thumbnailだけ別でissue立ててこちらは閉じます
