### ISSUE TITLE
official elasticsearch clientを使う

### ISSUE THREAD

**Issue by motoki317** [traPtitech/traQ#1804]
https://github.com/olivere/elastic はdeprecated
v8の対応はなされ無さそう

> Deprecated: Use the official Elasticsearch client for Go at https://github.com/elastic/go-elasticsearch

**Comment by ikura-hamu** [comment]
traQの [#team/SysAd/traQ/Server](https://q.trap.jp/messages/cd63aeef-e295-45ef-a550-2e2f258828bf) でのやり取り

> ikura-hamu: このissueについてですが、elasticsearchのバージョンを7から8に上げたほうがいいですか。公式ライブラリの仕様が7と8で大きく変わってそうなので、いつか変えるのだととしたら書き換えてる今やった方がいい気がします。

> toki: 詳しく見てないですがその方が都合がいいならいいと思います
でも書き換えるのと同時に7→8に上げるのは大変じゃないですか？（そうでもない？）
デバッグするときに書き換えが原因なのか7→8に上げたのが原因なのかわからなくなりそう

> ikura-hamu: ↑について、8の方のドキュメントを見たところ、今までのClientと別にTypedClientというのがあり、8のClientは7のとそれほど変わらない書き方、TypedClientは結構違う書き方でした。
なのでとりあえずは7のままで書こうと思います。
https://pkg.go.dev/github.com/elastic/go-elasticsearch/v8@v8.8.1#pkg-types
