### ISSUE TITLE
FCM APIの移行

### ISSUE THREAD

**Issue by logica0419** [traPtitech/traQ#1867]
https://firebase.google.com/docs/cloud-messaging/migrate-v1?hl=ja

**Comment by Nagarei** [comment]
リマインダーメール来てましたね
> We’re writing to remind you that starting June 20, 2024 the legacy Firebase Cloud Messaging (FCM) APIs will be discontinued.
>
>  Your recent usage of impacted APIs/features: Admin SDK(batch send API)

**Comment by Nagarei** [comment]
たぶんfirebaseのライブラリのバージョンを上げて、これを使えば良い
https://firebase.google.com/support/release-notes/admin/go#version_4120_-_12_july_2023

v3->v4なので工夫が必要そう？
https://firebase.google.com/docs/admin/migrate-go-v4
