### ISSUE TITLE
DBのDSN生成をライブラリに任せる

### ISSUE THREAD

**Issue by logica0419** [traPtitech/traQ#1873]
https://zenn.dev/mstn_/articles/75667657fa5aed

**Comment by logica0419** [comment]
ここ
https://github.com/traPtitech/traQ/blob/b20f8169c88d0dbdbb9661f35ffffe8a6cb00217/cmd/config.go#L391-L398

**Comment by ras0q** [comment]
`DSN`じゃなくてまんま`DSNConfig`使えたりする
https://pkg.go.dev/gorm.io/driver/mysql#Config

**Comment by logica0419** [comment]
神じゃん、それで
