### ISSUE TITLE
charsetの更新

### ISSUE THREAD

**Issue by logica0419** [traPtitech/traQ#1876]
>https://github.com/traPtitech/traQ/blob/master/compose.yaml#L53
寝る前に見かけたので
これもうconoha使ってないから
charactor-set=utf8mb4, colletaion=utf8mb4_general_ciでいいよ

**Comment by ISAWASHUN** [comment]
@logica0419 

初めまして、現在大学生のものです。logica0419さんの記事からこのOSSを見つけました。OSSに初めて貢献してみたいのですが、このisuueに取り組んでもよろしいでしょうか。

command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ciの部分を以下のように変更すればよろしいでしょうか。
charactor-set=utf8mb4, colletaion=utf8mb4_general_ci

**Comment by logica0419** [comment]
@ISAWASHUN 
logicaです。traQを見つけて下さり、ありがとうございます！
どの記事だったのかな…どれにせよとても嬉しいです。

修正方針についてですが、その変更方針で良いと思います。docker compose upしたらDB含め全コンテナが立ち上がり、問題なくtraQのローカル環境が動くことを確認できたらOKです。

**Comment by logica0419** [comment]
また、もう一つ修正して欲しい箇所がございまして、それがこちらの「make up-test-db」で立ち上がる、DB周りのテスト実行用DBです。
https://github.com/traPtitech/traQ/blob/master/Makefile#L31-L33
これはcompose.yamlで立ち上がるものとは別に定義されているので、こちらも修正が必要です。

Makefileの中でこちらのシェルスクリプトを呼び出しているので、該当箇所を同様に修正していただければ完璧です。
https://github.com/traPtitech/traQ/blob/master/dev/bin/up-test-db.sh#L18

それではよろしくお願いします！
プルリクエストお待ちしております〜

**Comment by Nagarei** [comment]
@logica0419 今更気が付いて申し訳ないのですが、 development.md をまた忘れていそう
https://github.com/traPtitech/traQ/blob/f56bccaba074cb32e679ffb5a3793399791e2c36/docs/deployment.md?plain=1#L399
