### ISSUE TITLE
DM

### ISSUE THREAD

**Issue by tohutohu** [traPtitech/traQ#203]
チャンネルをメッセージ送信時に作成するみたいな感じだったと思うんですけど、具体的な処理はどうするんでしょう

**Comment by tohutohu** [comment]
β出したいのでこれ作って欲しい
@masutech16 @wtks

**Comment by masutech16** [comment]
現在channelが決まってないとPOSTできないので、`POST users/{userID}/messages`でプライベートメッセージを送るようにします。(channel作成後は通常のAPIでも送れる
とりあえず今からこれを実装します

**Comment by n-inja** [comment]
DMが作成されているかどうかを`GET users`とかで取得できるといいですね

**Comment by masutech16** [comment]
どういう形式だとよいですかね。
自分との間に作られているチャンネルを{channelID, partnerID}の配列とかで返すとかでしょうか

あと、`POST users/{userID}/messages`はチャンネル作成の有無に関係なくメッセージを送れますが、それでも必要でしょうか
もしかして'GET users/{userID}/messages'とかで、DMのメッセージを取得できれば解決しますか？
