### ISSUE TITLE
botのbioをそれぞれの情報更新用APIで変更したい

### ISSUE THREAD

**Issue by oribe1115** [traPtitech/traQ#2035]
現在botやwebhookのbioを更新するには、それぞれのtokenなどを用いて`PATCH /users/me`を叩くという方法しかない

bot情報の更新用API`PATCH /bots/{botId}`や`PATCH /webhooks/{webhookId}`に`bio`のフィールドが追加されば、bot consoleからのbio更新も行えるようになる

**Comment by Takeno-hito** [comment]
webhook 、現状プロフィールを確認する手段がそもそもないので BOT のみ対応中
