### ISSUE TITLE
/users/me/subscriptions に未読管理チャンネルを含める

### ISSUE THREAD

**Issue by logica0419** [traPtitech/traQ#2269]
> 【内容】[`/users/me/subscriptions`](https://apis.trap.jp/#/me/getMyChannelSubscriptions)のレスポンスに未読管理チャンネルが含まれず、未読管理+通知のチャンネルのみが含まれる
【要望】未読管理チャンネルも含めてほしいです

> クエリパラーメーターでinclude_なんとかみたいなのをつけて、設定なしの時の挙動を前と同じにすれば後方互換性は保てますね

**Comment by 24take** [comment]
実際には未読管理も取得できているようです
https://q.trap.jp/messages/97d35fe6-b37d-4c74-bb8d-23fafb8ee5ab
