### ISSUE TITLE
複数人のprivateチャンネルの不具合

### ISSUE THREAD

**Issue by masutech16** [traPtitech/traQ#244]
複数人のプライベートチャンネル機能を実装するとバグります。
具体的に発生する条件を示します。
既にプライベートチャンネルAが存在していてAが{a,b,c}のメンバーを持っているとすると、{a,b}のようなメンバーを持つ新規プライベートチャンネルを作成するときに作成できず、bad requestを返すバグが発生します(router/channels.goで、メンバーを確認するコードを書いています)

**Comment by wtks** [comment]
直ってる
