### ISSUE TITLE
topicで空文字列更新ができない

### ISSUE THREAD

**Issue by masutech16** [traPtitech/traQ#245]
thanks to krotkaz

**Comment by wtks** [comment]
API直接叩くと空文字で更新できるのを確認したので、クライアントの問題です

**Comment by wtks** [comment]
model/channel.goのUpdate()内の`db.ID(channel.ID).UseBool().Update(channel)`を`db.ID(channel.ID).UseBool().MustCols().Update(channel)`に変更

**Comment by wtks** [comment]
直ってなかった
