### ISSUE TITLE
`OpenAPI.yaml`の`PUT /bots/:botid/icon`のDescriptionに1MBとあるが正しくは2MB

### ISSUE THREAD

**Issue by pikachu0310** [traPtitech/traQ#2468]
実装を見に行くと2MBだったのでミスっぽそう
![image](https://github.com/traPtitech/traQ/assets/17543997/c7787190-e682-4f6d-9fb4-0cee4916561e)

**Comment by kaitoyama** [comment]
webhookやuserもかも?

**Comment by kaitoyama** [comment]
みんなここを呼んでいるので全て2MB
https://github.com/traPtitech/traQ/blob/master/router/utils/process_image.go#L27
