### ISSUE TITLE
DELETE /users/me/starsとDELETE /users/me/unreadのリクエストボディを削除する

### ISSUE THREAD

**Issue by wtks** [traPtitech/traQ#274]
DELETEメソッドではリクエストボディを持ってはいけないらしいです

**Comment by masutech16** [comment]
確認したんですけどこれ既になくなってないですか？

**Comment by wtks** [comment]
どっちもあるが

**Comment by masutech16** [comment]
レスポンスと見間違えてました(ごめんなさい

**Comment by azonti** [comment]
`PUT /users/me/unread`で管理してほしい
GETして読んだやつを消した配列をPUT
全消しなら空の配列をPUTみたいに（伝わって）

**Comment by masutech16** [comment]
タイミングによっては同一アカウントの端末間でリクエストがコンフリクトする可能性があるので見送ります
