### ISSUE TITLE
dataに必要な情報

### ISSUE THREAD

**Issue by tohutohu** [traPtitech/traQ#300]
全部flatに入れてください

## Notificationの設定で設定できるやつ
* icon
  * 通知の時のアイコンpngとかのURL(今GitHubの通知にはtって出てる)
  * 形式：URL
* badge
  * Androidのステータスバーに出すアイコン的なの
  * モノクロ正方形の小さい画像
  * 形式：URL
* image
  * 通知を表示するときに大きい画像を付けられる
  * 可能ならメッセージに画像が添付されてるときに
  * 形式：URL
* tag
  * 通知を一つにまとめられるらしい
  * どうなるかわからないので試してみたい
  * 形式：ChannelID
* vibration
  * 通知のバイブ設定
  * 現行を踏襲するなら[1000, 1000, 1000]だったとおもう
  * 形式：整数の配列
* sound
  * 通知音
  * iZoo
  * 形式：URL

## ほしいデータ
* path
  * publicなら/channels/... privateなら/users/... みたいに完全なパスが欲しい
  * 形式：文字列
* body
  * 今の形からチャンネル名を除く感じで
  * 添付ファイルははimage とかfileで置換してくれると嬉しいかも
  * 形式：文字列
* title
  * チャンネル名
  * 形式：文字列

**Comment by wtks** [comment]
なんとですね、値はすべて文字列でないと送れません

**Comment by tohutohu** [comment]
jsonで受け取れるからいい感じにして欲しい
