### ISSUE TITLE
パッケージ管理をGo 1.11 Modules(vgo)にする

### ISSUE THREAD

**Issue by wtks** [traPtitech/traQ#341]

**Comment by tohutohu** [comment]
> Modules を使ってみて最も良いと思ったのは，やはり go get をするだけで依存パッケージを追加できるという最もシンプルなフローに戻ってこれることでした．また，git pull 直後など足りないパッケージがあれば勝手に落としてきてくれるのもかなり好印象です．Go にバンドルされると CI のセットアップ等が超楽になるのも嬉しい！
> 一方で，dep からの移行をいますぐやるかというとかなり悩ましいです．Modules は未だ Experimental なので何が起きるかわからないというのが大きな問題です．また，dep などからの移行パスが完全に用意されているわけではないので，そこそこの規模のプロジェクトではある程度歯を食いしばる覚悟が必要かもしれません．
[Go 1.11 の modules・vgo を試す - 実際に使っていく上で考えないといけないこと #golang | Wantedly Engineer Blog](https://www.wantedly.com/companies/wantedly/post_articles/132270)

> TL;DL
思った通りの状態にならない。
ライブラリ作者全員semverで殴って回る必要がある。
ログから情報が得られない。
実行もクソ遅い。
ゆえに辛い。
[vgoを今やり始めると辛いからやめとけ | vvakameさんの脳の肥やし](https://blog.vvaka.me/2018/06/08/vgo/)

やるのは良さそう
