### ISSUE TITLE
/messages/{messageId}のputメソッドのrequestBodyがない

### ISSUE THREAD

**Issue by masutech16** [traPtitech/traQ#35]
APIドキュメントの/messages/{messageId}のputメソッドには変更した内容を受け取るリクエストボディが必須だと思われますが、現在それがないため変更がサーバーに飛んでこない仕様になっています。
[参考](https://app.swaggerhub.com/apis/wtks/test/0.0.1#/message/editMessageById)

また受け取るときのjsonの形式ですが、どういう形式が良いかいまいちわかりません。個人的にはサーバーがクライアントに送る形式と同じが良いと思うのですがどうでしょうか。

**Comment by tohutohu** [comment]
リクエストボディはmessageのPOSTと同じでいいと思ったんですが、messageのPOSTと同じにした場合何か支障がありますかね？

**Comment by masutech16** [comment]
putの場合はpinとかの情報が取れないとまずいかなと思ってそう提案したのですが、pin等は別のAPIが用意されていましたね。
それならばPOSTと同じ形式で大丈夫です。
とりあえずPOSTと同じ形式で実装します

**Comment by tohutohu** [comment]
swagger.yamlも編集してmessageタグのブランチに上げてください。
#36
