### ISSUE TITLE
セッションの有効期限の自動更新(regenerate)

### ISSUE THREAD

**Issue by wtks** [traPtitech/traQ#355]

**Comment by tohutohu** [comment]
そういえばこれ関連サービスのクッキーも更新しないと、関連サービスにログインできなくなる気がした
だから実装されてなかったんだっけ

**Comment by wtks** [comment]
確かに。
楽そうな解決方法としておもいついたのは、他ドメインの期限が切れて、q.trap.jpのloginにリダイレクトしてきたときに、(q.trap.jpのセッションは更新されててログイン済みなので)そのままパイプラインにリダイレクトさせるようにtraQ-UIを変更

**Comment by ptr-yudai** [comment]
あー、関連サービスが動くかまではテストしてないです。このPRではダメぽいかな。

**Comment by tohutohu** [comment]
てことはUI側は
1. `/login`にアクセスがあったらまず`/users/me`とかを見てログインしているかを確認
2. ログインしている∧後ろにリダイレクト先のURLがある→パイプラインに, ログインしている∧リダイレクト先のURLがない→traQにって感じかな？

**Comment by wtks** [comment]
@tohutohu そうだね
@ptr-yudai UI側のコード変更で対応出来そうなので、このPR自体は問題ないと思います

**Comment by wtks** [comment]
@ptr-yudai 一応説明しとくと、(歴史的経緯から)他ドメインで動いてる部内サービスでログインユーザーの認証を行うためのcookieを付与するために、traQにログイン後pipelineっていうサービス(部内giteaのSysAdにリポジトリあり)でブラウザを各ドメインにリダイレクトでたらい回ししています

**Comment by ptr-yudai** [comment]
なるほどです。pipelineのコードも読んどきます。

**Comment by wtks** [comment]
#672
