### ISSUE TITLE
大量同時アクセスで`(driver: bad connection)`が発生する

### ISSUE THREAD

**Issue by wtks** [traPtitech/traQ#399]

**Comment by wtks** [comment]
サーバからの接続が切られたconnectionをプーリングしている可能性

**Comment by wtks** [comment]
参考：http://dsas.blog.klab.org/archives/2018-02/configure-sql-db.html

**Comment by wtks** [comment]
直ってない

**Comment by tohutohu** [comment]
これってどうやったら再現できる？

**Comment by wtks** [comment]
1度に数百リクエスト飛ばして、しばらくリクエストを控えてからまた1度に数百リクエスト飛ばす。
一定期間未使用のためにサーバからの接続が切られたコネクションをプーリングしてることが原因だと考えられるから、常時多くのリクエストが飛んでて、DBのコネクションを使用してたら起こらない(conohaのdbの最大接続数は30なので、単純計算で言うと常時３０以上のDBへのリクエストが飛んでたら起こらないはず)

**Comment by tohutohu** [comment]
リクエストはなんかコードとかありますか？

SetConnMaxLifetimeを短めに設定してやるとプーリングしたコネクションを閉じることになるから良さそうだけど

**Comment by wtks** [comment]
SetConnMaxLifetime設定したらbad connectionめちゃくちゃ多発したんだよな・・・

**Comment by tohutohu** [comment]
まじかISUCONのとき0にしてtoo many connectionを回避したけどこれには当てはまらんかな

**Comment by tohutohu** [comment]
SetMaxOpenConnsとかSetMaxIdleConnsとかは30以下になってるよね？

**Comment by wtks** [comment]
too many connectionはSetMaxOpenConnsで回避してる

**Comment by tohutohu** [comment]
これ本番環境で発生したことあるかな

**Comment by wtks** [comment]
ない

**Comment by wtks** [comment]
#772 のCheck connection liveness featureで直りそう
