### ISSUE TITLE
APIの単体テストを書く

### ISSUE THREAD

**Issue by wtks** [traPtitech/traQ#4]
httpリクエストハンドラー単位で書くこと

**Comment by wtks** [comment]
echoのハンドラーのテストコードの書き方は以下など参照
+ https://echo.labstack.com/guide/testing
+ https://dev.classmethod.jp/server-side/go16-echo-test/
+ https://dev.classmethod.jp/server-side/test-golang-echo-and-mysql/

**Comment by tohutohu** [comment]
現状書きながら進んでるので閉じます
なにかあればまた開いて
