### ISSUE TITLE
メッセージ埋め込み情報パーサーが不完全

### ISSUE THREAD

**Issue by wtks** [traPtitech/traQ#407]
utils/message/embedded.go

`!{ !{"type": "user", "raw": "@takashi_trap", "id": "dfdff0c9-5de0-46ee-9721-2525e8bb3d45"}`
のような形式のメッセージで埋め込み情報がパース出来ない。結果として通知が飛ばない等の問題が発生

**Comment by wtks** [comment]
https://github.com/traPtitech/traQ/blob/master/utils/message/embedded.go

**Comment by n-inja** [comment]
クライアント側はjsonのparseに失敗したら探索位置戻してる
