### ISSUE TITLE
通知が複数件送られてくる

### ISSUE THREAD

**Issue by tohutohu** [traPtitech/traQ#410]
![img_2aa5e6f3e13c-1](https://user-images.githubusercontent.com/19851537/52491964-a2da7900-2c0b-11e9-8e73-cf87a5211633.jpeg)

iOSだけでなだけでなくAndroidでも発生する
#zs チャンネルでは起きたのを確認していない

**Comment by tohutohu** [comment]
#gps チャンネルでも発生した
６件メッセージ送って３件同じ通知が来た

**Comment by tohutohu** [comment]
![img_c1eb037cc9c3-1](https://user-images.githubusercontent.com/19851537/52492277-32802780-2c0c-11e9-9bd2-d719e3db32f2.jpeg)

**Comment by wtks** [comment]
サーバーサイド側では一旦解決したということで
