### ISSUE TITLE
write: broken pipeエラーが発生する

### ISSUE THREAD

**Issue by wtks** [traPtitech/traQ#491]
https://www.techscore.com/blog/2017/12/05/go_broken-pipe/

**Comment by tohutohu** [comment]
どのエンドポイントで起きてるかは特定済み？

**Comment by wtks** [comment]
どのエンドポイントでも起こりうる。ログから消したい

**Comment by tohutohu** [comment]
クライアントがレスポンスを返す前に切断してくると発生するの

**Comment by wtks** [comment]
そう

**Comment by wtks** [comment]
#488 これ直したら起こらなくなった
