### ISSUE TITLE
GET系のAPIにLast-Modified/ETagヘッダーによるキャッシュを導入

### ISSUE THREAD

**Issue by wtks** [traPtitech/traQ#506]
を試みる

**Comment by tohutohu** [comment]
やるならクライアントのAxios側の対応も必要

**Comment by wtks** [comment]
あーそれはめんどうだからやめるか

**Comment by tohutohu** [comment]
この際だからfetchに全部置き換えるという説がある
fetch使ってService Workerでよしなにするかfetch自体に304を解釈する仕様がありそう(`cache`ってオプションなんだけどググっても全然情報がなくて悲しい)

**Comment by tohutohu** [comment]
https://fetch.spec.whatwg.org/#concept-request-cache-mode
あった fetch使えば全て解決では？

**Comment by wtks** [comment]
はいプロさんがいいねしました

**Comment by tohutohu** [comment]
各種ロードの通信量も減るしいい事づくしだったりしないかな
