### ISSUE TITLE
BOTイベントでユーザーIDや表示名もペイロードにのせる

### ISSUE THREAD

**Issue by tohutohu** [traPtitech/traQ#567]
Botとして運用する場合必要となることが多い
メンションを返す時にも必要

**Comment by tohutohu** [comment]
@wtks 
これQSoCでtokiくんに任せてもいい？
あと#traQのチャンネル作成の機能をBotに追加するところまで

**Comment by wtks** [comment]
いいよ(ただ、こっちでもまだBOT部分に若干手を入れる可能性が高い)
ちなみにチャンネル作成通知BOTはもう作れるはず

**Comment by wtks** [comment]
@tohutohu

**Comment by tohutohu** [comment]
チャンネル作成通知BOT作るならチャンネル名とかも一緒に出したいけどpayloadにはchannel_idしか載ってないからAPIでチャンネル名とか取らないといけなくてめんどいよね？

**Comment by wtks** [comment]
https://github.com/traPtitech/traQ/blob/b57efb53dcba5fdf0be1cddce44a902b801d7a17/bot/payload.go#L47
チャンネルのパスは返してるから親チャンネルとか辿る必要はない。ただ、作成ユーザーはIDしか返してないね

**Comment by tohutohu** [comment]
あーそうだった
issue名もそうじゃん

作成ユーザーのIDと表示名も載せるようにして、BOT作ってもらいますね
新入部員のBotと統合したほうがいい？それとも別に作ったほうがいい？

**Comment by wtks** [comment]
統合していいと思う
