### ISSUE TITLE
OGPクローラー

### ISSUE THREAD

**Issue by wtks** [traPtitech/traQ#582]
UI側でOGPを表示するために必要

**Comment by tohutohu** [comment]
毎回本家にアクセス飛ばすのはやばいから、なんかでキャッシュが必要そう(redisとか)

**Comment by wtks** [comment]
普通にMariaDBに突っ込めばいいんじゃないかなと思った

**Comment by tohutohu** [comment]
更新される可能性もあるからそこらへんをよしなにな(redisなら自動で消せる)(redisって言ったのはただかっこいいからですすまん)

**Comment by spaspa** [comment]
:memo:TwitterとかはJS実行しないと適切な結果が得られないので

- 別の埋め込み方法を提供する
  - 読み込む必要のあるscript指定など
- JSを実行する

のどちらかをしないとまともに表示できない
