### ISSUE TITLE
Activityで通知フィルタリングすると全体通知チャンネルが表示されない

### ISSUE THREAD

**Issue by motoki317** [traPtitech/traQ#654]
/activity/latest-messages で subscribe: true と送ると, 全体通知チャンネル（#random等）が"通知を付けていない"扱い?になって一覧で帰ってこない
subscribe: false だと普通に帰ってくる

意図していない動作？

**Comment by wtks** [comment]
/activity/latest-messagesでsubscribeをtrueにした場合は、リクエストしたユーザーが購読しているチャンネルを`users_subscribe_channels`テーブルを見て取得し、フィルタリングを行なっているんですが、全体通知チャンネルの購読情報は`users_subscribe_channels`に無いので、そういうことになってしまっています

全体通知チャンネルもレスポンスに含めたほうが健全
