### ISSUE TITLE
同時大人数接続で重くなる

### ISSUE THREAD

**Issue by motoki317** [traPtitech/traQ#656]
同時に大人数（100人とか）で接続するとめっちゃ重くなる
一つサーバーを借りてtraQサーバー環境を建てて, ベンチマークみたいにして色々調べていく

#399 関係ありそう？

**Comment by Nagarei** [comment]
eiya：僕コラボレーターですらなかったので自分にAssigneできなかった（悲しい）

**Comment by sapphi-red** [comment]
refs? #506 #613 #615 #635

**Comment by wtks** [comment]
traQ自体が重くなるのもあるんですけど、traQの外(Linux Kernelだとかネットワークだとか別に動いてるソフトウェア)の問題がわりとあります

**Comment by Nagarei** [comment]
テスト用サーバーってもう建ってるんですか(こういう会話traQとissueとどちらが良いんだろうか)

**Comment by sapphi-red** [comment]
たぶんまだかと

聞くのはtraQのrandomのが見る頻度が高い人が多そうなんでそっちのほうがいいかなって思います

**Comment by Nagarei** [comment]
ここでDBに接続してる
https://github.com/traPtitech/traQ/blob/master/router/middleware.go#L112
```
SELECT * FROM `users`  WHERE (`users`.`id` = '4c34b3b7-0532-4a93-a1a2-3a991a0ca446') ORDER BY `users`.`id` ASC LIMIT 1
```
本当にここが重いのかは知らない

**Comment by Nagarei** [comment]
↑重そう  
topで見たときにネックになっている  
偶にmysqlがToo many connectionsで落ちる

**Comment by Nagarei** [comment]
メモリネックでは無さそう（123MBくらいしか使ってない）
