### ISSUE TITLE
アンケート機能

### ISSUE THREAD

**Issue by wtks** [traPtitech/traQ#72]
GoogleフォームだといちいちtraqIDを入力したり、回答を修正するために複数回回答し、集計が二重にされたりしてアレって聞いたからtraQに統合したい。
あとアンケートのリマインダーを自動で行ったり(通知を飛ばす)、全員回答のアンケートに回答するまで何らかの形で画面上に表示し続ける(もっと言うと、回答するまでtraQの機能制限(使えなく)したり)(僕みたいに全員回答のアンケート後回しにして結局回答しない人いるので)。

**Comment by kaz** [comment]
部員管理のほうにつける案もありますが、
仰るような密接な連携を追加するとなるとどっちが良いのか微妙ですね

webhook/plugin的なので連携できないかしら
