### ISSUE TITLE
botのMESSAGE_CREATEDイベントのuserのdisplay_nameが空になることがある

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/traQ#756]
nameとdisplay_nameが一致している場合？
display_nameを一度も変更していない場合？

**Comment by wtks** [comment]
DBから取ってきたやつをそのまま返してるので、表示名を空にしてる人は空のまま返してる。
/usersのレスポンスでは、空の場合はnameをいちいち突っ込んで返してる(ので、表示名をnameと同じに設定しているように見える)
