### ISSUE TITLE
メッセージ検索

### ISSUE THREAD

**Issue by wtks** [traPtitech/traQ#8]
# 検索でしたいこと
+ and, or, minus
+ from : 誰のメッセージか
+ to   : 誰へのメッセージか
+ since : いつから
+ until : いつまで
+ channel : どのチャンネルのメッセージか
+ limit : 取得数制限

**Comment by wtks** [comment]
PEG(Parsing Expression Grammars)を使って検索クエリをパースする？
参考：https://github.com/tweetdeck/twitter-search-query-parser

**Comment by wtks** [comment]
epic/search ブランチで開発開始

**Comment by FujishigeTemma** [comment]
memo: https://md.trap.jp/xzcB0DuaTgipN2iqaKe6bw
