### ISSUE TITLE
[swagger.yaml] clipタグの型が違う

### ISSUE THREAD

**Issue by kaz** [traPtitech/traQ#82]
- POST /users/me/clips
- DELETE /users/me/clips

のmessageIdが`int`になってる

他にも同様のミスがあるかも

**Comment by azonti** [comment]
`PUT /channels/{channelId}/notifications`のexampleは`UserNotificationList`を使うべきでは

**Comment by azonti** [comment]
`GET/PUT /users/me/channels/visibility`のexampleも一部`integer`になってる
