### ISSUE TITLE
PUT/DELETE /channels/{channelId}/pinはpath parameterを使うべき

### ISSUE THREAD

**Issue by azonti** [traPtitech/traQ#83]
`PUT /channels/{channelId}/pin/xxxxxxxx-xxxx-xxxx-Nxxx-xxxxxxxxxxxx`
`DELETE /channels/{channelId}/pin/xxxxxxxx-xxxx-xxxx-Nxxx-xxxxxxxxxxxx`という感じで

**Comment by tohutohu** [comment]
つまり
/channels/{channelId}/pin/{messageId}
ってことですかね？

**Comment by azonti** [comment]
そうです
