### ISSUE TITLE
ユーザー新規登録

### ISSUE THREAD

**Issue by wtks** [traPtitech/traQ#833]
traP内では使わない。外部インスタンス向け用

**Comment by sapphi-red** [comment]
現状だとログインできてかつ登録権限のあるユーザーがエンドポイントをたたく必要がある

**Comment by motoki317** [comment]
configに`allowSignUp`（default: false）のような設定を追加して、これがfalseのときは`POST /api/v3/users`を叩ける権限は従来通り、trueのときは誰でも叩けるようにする
`GET /api/v3/version`のレスポンスの`flags`に、`POST /api/v3/users`を誰でも叩けるかが分かるように、`signUpAllowed`を追加する

という感じで考えています

**Comment by sapphi-red** [comment]
よさそうです
