### ISSUE TITLE
同じ人が同じコメントに何度もスタンプを押した場合について

### ISSUE THREAD

**Issue by azonti** [traPtitech/traQ#85]
`GET /messages/{messageId}/stamps/{stampId}`が数の情報を含んでいないのですがどうなるのでしょうか

**Comment by kaz** [comment]
これ、多分StampDetailのリストである必要がありますよね

そもそも投稿についてるスタンプを`stampId`ごとに取得するの、非効率だし需要がなさそうなので、

- MessageにStampDetailのリストを含める
- `GET /messages/{messageId}/stamps`を用意

とかにしたらどうでしょう

**Comment by wtks** [comment]
#177 で色々修正した
