### ISSUE TITLE
WSで`viewstate:null`を受信後に該当コネクションの送信バッファが詰まる

### ISSUE THREAD

**Issue by wtks** [traPtitech/traQ#864]

**Comment by wtks** [comment]
index out of rangeでpanicしてる

**Comment by sapphi-red** [comment]
これ、RTCのほうと合わせて`viewstate:`にしますか？

**Comment by wtks** [comment]
鯖の実装の方では`viewstate:null`も`viewstate:`も対応してるのでどちらでもいいですよ

**Comment by wtks** [comment]
(ちなみに`viewstate:`にしてもpanicは #865 を取り込まないと回避できない)

**Comment by sapphi-red** [comment]
合わせたほうがきれいそうなので合わせます :+1:
