### ISSUE TITLE
全取得系APIのレスポンスを使い回す

### ISSUE THREAD

**Issue by wtks** [traPtitech/traQ#877]
- [x] 公開チャンネル一覧
- [ ] 有効ユーザー一覧
- [x] スタンプ一覧
- [ ] ユーザーグループ一覧

**Comment by wtks** [comment]
#878

**Comment by wtks** [comment]
#895

**Comment by motoki317** [comment]
ユーザー一覧とグループ一覧は内部で使いまわしてないけどまたパフォーマンスが問題になったら新しくissueを立てる
