### ISSUE TITLE
nobodyID,noSuchMessage,noSuchChannelなどが欲しい

### ISSUE THREAD

**Issue by azonti** [traPtitech/traQ#88]
存在しないことが保証されてる`nobodyID`とか`noSuchChannel`とか欲しい

**Comment by AzonTi** [comment]
あと`stars_test.go`とかは勝手に生成してるけどtestChannelもあっていいと思う

**Comment by AzonTi** [comment]
存在しないことが保証されてるNobodyIDとかNoSuchCannelIDとかも欲しい

**Comment by wtks** [comment]
uuid.NewV4()すれば絶対(100%じゃないが有り得ない)かぶらないので要らないかと
