### ISSUE TITLE
Webhookユーザーにタグがつけられる

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/traQ#887]
これは意図してる仕様ですか？

**Comment by wtks** [comment]
1.0APIの時から特に制限してないですね。問題があるなら制限してもいいです

**Comment by sapphi-red** [comment]
つけられないほうが統一されてる感があるのとつけられなくても問題なさそうなので制限してもいいかなって個人的には思います
/cc @spaspa 
refs traPtitech/traQ_S-UI#772

**Comment by spaspa** [comment]
UI上制限してるのにAPIから設定できる……ってのも少し気持ち悪いので制限しちゃっていいかと
