### ISSUE TITLE
pathのId,IDの表記ゆれ

### ISSUE THREAD

**Issue by masutech16** [traPtitech/traQ#90]
main.go内でpath paramsにIdとIDの表記ゆれがあります。

例)
messages/:messageId/ と messages/:messageID

ここで指定した名前を使ってデータを取得するのでこれが違うとうまく受け取れないという事態が予想されます。
そこでどちらかに統一した方が良いと思うのですが、どちらのほうがよいでしょうか。
IDはサーバー側のスクリプト内で統一されて気が楽です。
Idだとswaggerの名前と同じになる程度です。

個人的にはIDでそろえてswaggerもそれに倣うのが良いと思うのですがどうでしょう。

**Comment by tohutohu** [comment]
レスポンスで返すものはId、それ以外はすべてIDで統一するという方針です
