### ISSUE TITLE
チャンネルのアーカイブを子チャンネルに対して再帰的に行う

### ISSUE THREAD

**Issue by wtks** [traPtitech/traQ#905]
逆に親チャンネルがアーカイブされていた場合は、その子チャンネルはアーカイブ解除出来ないようにする

**Comment by Kejuntrap** [comment]
する予定. -> します

**Comment by Kejuntrap** [comment]
@Kejun

**Comment by Kejuntrap** [comment]
@Kejuntrap (最初の５文字です）

**Comment by wtks** [comment]
振る舞いの仕様

1. チャンネルのarchived属性をtrueにした場合に、その全ての子孫チャンネルもarchived属性をtrueにする
2. チャンネルのarchived属性をfalseにしようとした場合、
   1. その親チャンネルがarchived = trueだった場合は、処理を拒否する(エラー)
   2. その親チャンネルがarchived = falseだった場合は、archived属性をfalseに変更する。但し、子孫チャンネルはそのままにする
3. ルートチャンネルの親(実体は無い)は常にarchived = false
4. archived属性がtrueのチャンネルの親チャンネルは変更禁止(エラー)
   + チャンネルの移動ができないという事
5. archived属性がfalseのチャンネルの親チャンネルを、archived属性がtrueなチャンネルに変更する事は出来ない(エラー)
   + アーカイブ中のチャンネルの子になる事は出来ないという事

**Comment by wtks** [comment]
↑要するに、アーカイブされてるチャンネルの子孫チャンネルも絶対にアーカイブされているという条件です

**Comment by sapphi-red** [comment]
- archived属性がfalseのときにarchived属性をtrueにしつつ、親チャンネルを変更した場合

これどうしますか？(できてなくてもよさそう)

**Comment by wtks** [comment]
archived属性の再帰的な変更処理は特殊なので、他の変更と同時に行えなくて、アトミックな処理になると思います。

**Comment by wtks** [comment]
実装メモ (必要な情報全てが書かれているとは限らないです) 

+ `github.com/traPtitech/traQ/service/channel`パッケージ以下にチャンネルを管理・操作するような処理が実装されている
  + サーバー内部では、チャンネルの木構造を`github.com/traPtitech/traQ/service/channel.Tree`インターフェースとその実装の`github.com/traPtitech/traQ/service/channel.treeImpl`構造体で保持している
  + `github.com/traPtitech/traQ/service/channel.Manager`インターフェースとその実装の`github.com/traPtitech/traQ/service/channel.managerImpl`構造体で、チャンネルの情報を管理・操作している
+ DBと`channel.Manager`のやり取りは、`github.com/traPtitech/traQ/repository.ChannelRepository`インターフェースとその実装の`github.com/traPtitech/traQ/repository.GormRepository`構造体(の`channel_impl.go`)を介して行われている
+ チャンネルのarchived属性の再帰的な変更操作はアトミック
  + 中途半端に処理する事は出来ない
  + 「指定したチャンネルとその子孫チャンネルのアーカイブ属性が**全て変更される**」か、「指定したチャンネルとその子孫チャンネルのアーカイブ属性が**一つも変更されない**」のどちらか
  + という事なので、DBの更新処理は全体でトランザクションを取って行う必要があります。

+ 現状、`channel.Manger`の`UpdateChannel`でarchived属性の変更処理が行われているけど、別の関数(`ArchiveChannel`, `UnarchiveChannel`みたいな？)に切り出したほうが良さげ
+ DBのトランザクションを取るためにも、同様に`repository.ChannelRepository`の`UpdateChannel`もアーカイブに関する処理だけ別にした方が良さげ

**Comment by wtks** [comment]
振る舞いの仕様に書き忘れてたんですけど、アーカイブされたチャンネルを親として新しいチャンネルを作るのも禁止です

**Comment by Kejuntrap** [comment]
仕様5の
- archived属性がfalseのチャンネルの親チャンネルを、archived属性がtrueなチャンネルに変更する事は出来ない(エラー)
     - アーカイブ中のチャンネルの子になる事は出来ないという事

のところがよくわかっていないのですが、
archivedがfalseのチャンネルの親チャンネルを、archivedをtrueにした場合、archivedがfalseのチャンネルはarchivedがtrueになるだけではないのですか？

**Comment by wtks** [comment]
```
.
└── a
    ├── b - archived
    │   └── c - archived
    ├── d 
    │   └── e
    └── f
```
っていう状態で、dの親をfに変更(移動)できても、
```
.
└── a
    ├── b - archived
    │   └── c - archived
    └── f
        └── d 
            └── e
```
dの親をbやcに変更する事はできないということです
```
.
└── a
    ├── b - archived
    │   ├── c - archived
    │   └── d <- NG
    │       └── e <- NG
    └── f
```

**Comment by Kejuntrap** [comment]
archivedがfalseのチャンネル移動に関しての仕様なんですね　わかりました

**Comment by wtks** [comment]
確かに日本語が曖昧でしたね🙇‍♂️

**Comment by wtks** [comment]
現状のアーカイブ処理(指定したチャンネルのみアーカイブ。子チャンネルや親の状態を見ない)の流れをまとめておくと、
1. クライアントのjsonリクエストを構造体に受け取る
https://github.com/traPtitech/traQ/blob/b03839405c5302e2cdb2da0ec67c0d8c5ae47ec9/router/v3/channels.go#L89
https://github.com/traPtitech/traQ/blob/b03839405c5302e2cdb2da0ec67c0d8c5ae47ec9/router/v3/channels.go#L104
2. APIハンドラがChannelManagerのUpdateChannelを呼び出す
https://github.com/traPtitech/traQ/blob/b03839405c5302e2cdb2da0ec67c0d8c5ae47ec9/router/v3/channels.go#L116
3. ChannelManagerはそのまま引数をrepositoryのUpdateChannelに回す
https://github.com/traPtitech/traQ/blob/b03839405c5302e2cdb2da0ec67c0d8c5ae47ec9/service/channel/manager_impl.go#L209
(但し、https://github.com/traPtitech/traQ/blob/master/service/channel/manager_impl.go#L136 でロギング処理を間に挟む)
4. repository.UpdateChannelがDBのチャンネルのisVisibleを書き換える
https://github.com/traPtitech/traQ/blob/b03839405c5302e2cdb2da0ec67c0d8c5ae47ec9/repository/channel_impl.go#L107
5. DBの書き込みが成功した場合は、チャンネルツリーを更新する
https://github.com/traPtitech/traQ/blob/b03839405c5302e2cdb2da0ec67c0d8c5ae47ec9/service/channel/manager_impl.go#L217
https://github.com/traPtitech/traQ/blob/b03839405c5302e2cdb2da0ec67c0d8c5ae47ec9/service/channel/tree_impl.go#L252
