### ISSUE TITLE
リクエスト内の各種IDの検証

### ISSUE THREAD

**Issue by wtks** [traPtitech/traQ#91]
APIで送られてくるリクエストにある各種IDが本当に存在するものかどうかを確認する関数群の実装

**Comment by wtks** [comment]
DBにINSERTする系はテーブルに外部キー制約を貼るっていう手もあるが、これをすると単体テストの前準備が更に必要。あと若干DBが重くなるらしい。

**Comment by tohutohu** [comment]
いくつかのモデルにはExistsって関数あるけどそんな感じでいいんですかね

**Comment by masutech16** [comment]
やります
