### ISSUE TITLE
ユーザーの所属等をタグで表現する

### ISSUE THREAD

**Issue by wtks** [traPtitech/traQ#92]
現在の通知の実装では、`@タグ名`で特定のタグを持つユーザーに対して一括で通知を飛ばすことが出来るようにしているが、全員・学年・プロジェクトなどに通知を飛ばしたい場合、`everyone`とか`16`とか`制作プロジェクト名`等をタグとしてユーザーに予めつけておいて、`@タグ名`を利用することで通知を飛ばしたい。
この場合、Tagsテーブルにフラグを追加して、管理人でないと追加・削除できないタグを実装する必要がある。

**Comment by n-inja** [comment]
`/\d{2}[B|M|D]/`のタグを管理者だけが操作できるようにしてほしい
