### ISSUE TITLE
親チャンネル変更時の深さ判定が5以内から5未満になっている

### ISSUE THREAD

**Issue by FujishigeTemma** [traPtitech/traQ#933]
#gps/times/mazrean/yuri/testを移行しようとしたときに、channel depth exceededで怒られました。

**Comment by sapphi-red** [comment]
#gps/times/mazrean/test => #gps/times/mazrean/yuri/test にうつそうとしたとき

**Comment by kamecha** [comment]
kamechaです
QSoCでやってみたいと思います

**Comment by wtks** [comment]
このバグに関連してそうな箇所を貼っときます
親チャンネル変更処理: https://github.com/traPtitech/traQ/blob/eb75c7cd27de6ce8fbcc2e767b8b75085732d5d0/service/channel/manager_impl.go#L190
そのテストコード: https://github.com/traPtitech/traQ/blob/eb75c7cd27de6ce8fbcc2e767b8b75085732d5d0/service/channel/manager_impl_test.go#L397

今回はテストコードが書かれてるのにバグになってしまってるんですが、それはテストケースの質が悪いからテストが通ってしまってます。なので、イシューに書かれてる状況を再現するようなテストコードのケースも追加してほしいです
