### ISSUE TITLE
windowsでmakeが動かない

### ISSUE THREAD

**Issue by Nagarei** [traPtitech/traQ#936]
書かれているのがLinux用のコマンドなので
優先度は低め

**Comment by Nagarei** [comment]
`SOURCES ?= $(shell find . -path "./vendor" -prune -o -type f -name "*.go" -print)`
と
`@curl -L -Ss https://github.com/traPtitech/traQ_S-UI/releases/latest/download/dist.tar.gz | tar zxv -C ./dev/frontend/ --strip-components=2`
が原因な気がする（他にもあるかもしれない）
update-frontendってgit cloneでも良いように見えるけどどうなんだろう

**Comment by ras0q** [comment]
brewとかでもそのままだと動かなそうです
https://q.trap.jp/messages/1702533f-9776-48f8-9dac-806d7f2290f0
https://q.trap.jp/messages/fd6b9ea2-d118-4f7e-9dae-5dad4b08eb91

**Comment by motoki317** [comment]
/stale

WSLで統一してもらい、Windowsのサポートは切った方が良いと思う

強い異論があれば受け付けます
