### ISSUE TITLE
凍結済みユーザーにメンションでの通知が行く

### ISSUE THREAD

**Issue by ryoha000** [traPtitech/traQ#947]
らしい

**Comment by spaspa** [comment]
埋め込みを直接投稿した際に通知が飛んでしまうようです (@〇〇の置換は起こらなかった)
booQの自動投稿メッセージで頻発しているっぽい

**Comment by wtks** [comment]
https://github.com/traPtitech/traQ/blob/2a38721a5130b14d3c054f22ec1814d0095e2f98/service/notification/handlers.go#L162

**Comment by motoki317** [comment]
もしかしてグループのメンション通知も飛んでます？
https://github.com/traPtitech/traQ/blob/master/service/notification/handlers.go#L168-L177

**Comment by wtks** [comment]
グループは飛んでないです。グループメンバーの取得クエリで非アクティブユーザーは弾いてます
https://github.com/traPtitech/traQ/blob/2a38721a5130b14d3c054f22ec1814d0095e2f98/service/notification/handlers.go#L122

**Comment by wtks** [comment]
直接`!{...}`形式で埋め込んだユーザーメンションだけ飛んじゃってる
