### ISSUE TITLE
ルートチャンネルにチャンネルを移動できない

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/traQ#958]
`#z/aaaa`を`#aaaa`にしようとして
`PATCH /api/v3/channels/c4cb71b0-57bc-42a2-a4ec-01604875420c`
```plain
archived: false
force: false
parent: "00000000-0000-0000-0000-000000000000"
```
をすると`channel name conflicts`が返ってくる
`#aaaa`が存在しないことは確認済み

名前の変更を移動と同時に行った場合は問題なく移動できる

https://github.com/traPtitech/traQ/blob/828ba1b58116e552ebaccf37e9f6175a43defb5b/service/channel/manager_impl.go#L148-L170
null UUIDを渡したときに`if args.Parent.Valid`が`false`になってたりする？

**Comment by wtks** [comment]
ステージング環境でzz/aaaaを上に書かれているとおりのリクエスト飛ばしたら正常に移動できたようですが

**Comment by wtks** [comment]
あ、本番環境でそうなるのなら多分バグで、今のリリースはそもそもチャンネルマネージャー実装前ですね(1ヶ月以上バージョン上げてない)

**Comment by sapphi-red** [comment]
今ステージング環境で試したらダメでした

やった手順は
1. #aeeeee => #z/aeeeee (これは正常にできる)
1. #z/aeeeee => #aeeeee (これでエラーが出る)

なので何らかの不整合とかだったりするのかもしれません

**Comment by wtks** [comment]
確認した。元に戻そうするとダメっぽいですね

**Comment by wtks** [comment]
https://github.com/traPtitech/traQ/blob/6f4463ba7120d13627c47bcad0c977c8b5708d75/service/channel/tree_impl.go#L223
ここで、nilだった場合に、ct.rootsから削除してないのが問題っぽいです
